### ISSUE TITLE
运行时出现unable to load DLL'libs\texthost.dll'

### ISSUE THREAD

**Issue by qwshizou** [luojunyuan/ErogeHelper#11]
Unable to load DLL 'libs\texthost.dll' or one of its dependencies: 找不到指定的模块。(0x8007007E)

[![9DDK3G3YB{3A31400WCFSN2](https://user-images.githubusercontent.com/85842803/121839999-cf3bbe00-cd0d-11eb-859b-8a4252c08434.png)
](url)

**Comment by luojunyuan** [comment]
duplicate #9 
今后会增加缺少vcredist依赖的提示
