### ISSUE TITLE
反馈一些小问题，以及一些建议

### ISSUE THREAD

**Issue by IwakuraLain1984** [luojunyuan/ErogeHelper#12]
只是作为一些使用了各种软件仍然找不到完美软件的日语学习者提供一点自己的想法……仅供参考，
先说三个使用中小问题
1、当字幕开始工作后，所有偏好设置里的下拉框和文本框均会因为字幕频繁获得焦而难以操作
2、全屏模式下，启用“使用可自由移动的文本窗口”后，字幕框会变成一小块，也无法拉大或者在调整最大文本接受长度里改变长度，而且怎么都不显示日文。关闭“使用可自由移动的文本窗口”后正常，不使用全屏模式也正常。
3、有时候字幕框会莫名其妙的消失，如果加个重置字幕框位置\状态的功能说不定可以解决。

然后说一点点建议……只是基于个人角度使用角度，也许没啥实现的意义。
1、我注意到查字典的时候可以选取和调整输入字典的文本，用以应对分词诡异的情况，但可否直接提供一个功能，让其在字幕框里就可以直接的选取\复制，这样能直接配合类似沙拉查词这样的外部词典聚合，会比内置词典扩展性更好一些。
2、VNR有自动使用类似Voiceroid的TTS，根据人名读旁白\手动按键读提取到的文本功能，这个功能有时候还挺不错的。

感谢您的辛苦，软件还是很好用的。

、

**Comment by luojunyuan** [comment]
文本窗口在0.0.9版本中完全重置，有更好的交互体验，但是还没有实装，这里所有提到窗口问题都将不再出现（仿照vnr的“手动拖动改变宽度”与“自动改变的窗口高度”）

感谢建议，锁定文本框是个好主意。
