### ISSUE TITLE
启动时钟机关的Ley line会崩溃

### ISSUE THREAD

**Issue by Eveninger** [luojunyuan/ErogeHelper#20]
native版弹窗“ErogeHelper已停止工作”
any cpu版会弹窗“Timeout!Game window not found”

**Comment by luojunyuan** [comment]
可以告诉我你的游戏是steam还是什么版本吗？以及你的windows系统版本是什么。

**Comment by Eveninger** [comment]
> 可以告诉我你的游戏是steam还是什么版本吗？以及你的windows系统版本是什么。

资源是在[这里](https://yngal.com/gamedetails?id=554)下载的(备注：已打官方修正补丁v1.1；已打【A.T.Field汉化组&Arcus汉化组】《時計仕掛けのレイライン -黄昏時の境界線-》汉化补丁v1.11)
设备：小米平板2
版本：Windows 10 家庭版
版本号：22H2
操作系统内部版本：19045.2965
体验：Windows Feature Experience Pack 1000.19041.1000.0

**Comment by luojunyuan** [comment]
谢谢你提供的信息，我做了一点简单的修改，请你用下面这个版本打开Preference，通过Advance下面的下拉框，选择正在运行的游戏，start。试试看还会不会Timeout

[ErogeHelper.1.0.3.0.netfx.AnyCPU.zip](https://github.com/luojunyuan/ErogeHelper/files/11645810/ErogeHelper.1.0.3.0.netfx.AnyCPU.zip)

**Comment by luojunyuan** [comment]
1. native版本错误不太好追踪，我想要了解native版本里是直接点开ErogeHelper.exe也会出错吗？Preference.exe能够打开吗。

2. 因为我用了比较奇葩的方式来启动游戏（通过游戏路径）以及寻找游戏窗口，所以可以预见经常可能会超时，找不到游戏。这一点只能慢慢优化来排除了。

**Comment by Eveninger** [comment]
> 谢谢你提供的信息，我做了一点简单的修改，请你用下面这个版本打开Preference，通过Advance下面的下拉框，选择正在运行的游戏，start。试试看还会不会Timeout
> 
> [ErogeHelper.1.0.3.0.netfx.AnyCPU.zip](https://github.com/luojunyuan/ErogeHelper/files/11645810/ErogeHelper.1.0.3.0.netfx.AnyCPU.zip)

抱歉这么久才恢复，试了几次，现在启动是没有问题了。但是会出现点击失效的现象，这个游戏在平板上也是需要点击两次或者滑动才可以继续游戏，现在无论是否开启Assistive Touch，点击都无效，可以选中菜单项，但不可以点击（感觉像是只有第一次点击生效）。多次尝试过程中，只有一次是正常的，其他都是点击无效的情况

**Comment by Eveninger** [comment]
> 



> 1. native版本错误不太好追踪，我想要了解native版本里是直接点开ErogeHelper.exe也会出错吗？Preference.exe能够打开吗。
> 2. 因为我用了比较奇葩的方式来启动游戏（通过游戏路径）以及寻找游戏窗口，所以可以预见经常可能会超时，找不到游戏。这一点只能慢慢优化来排除了。



> 1. native版本错误不太好追踪，我想要了解native版本里是直接点开ErogeHelper.exe也会出错吗？Preference.exe能够打开吗。
> 2. 因为我用了比较奇葩的方式来启动游戏（通过游戏路径）以及寻找游戏窗口，所以可以预见经常可能会超时，找不到游戏。这一点只能慢慢优化来排除了。

1. 我尽可能描述下启动的现象。native版本是打开以后，屏幕中间会有icon出现，2-3秒左右游戏启动（**正常启动游戏，游戏会自动打开的。而通过ErogeHelper启动，游戏是最小化在桌面任务栏，需要手动点击一下**）然后大概10秒左右，会弹出“已停止工作”的弹窗。
2. Preference.ext可以正常打开

**Comment by Eveninger** [comment]
> 
抱歉抱歉，经过测试，是因为我默认用管理员模式启动Preference.exe才会导致点击失效的问题，正常启动就好了。不好意思~~

**Comment by Eveninger** [comment]
> 无事解决就好~
> 
> 我会加一个管理员模式的弹窗提示。


https://github.com/luojunyuan/ErogeHelper/assets/12775863/534a0980-0f0a-46f3-8bbd-536727046ceb

我再反馈一个ErogeHelper点击无效的问题吧

**Comment by luojunyuan** [comment]
我发布了新的release，这个问题应该被解决了
