### ISSUE TITLE
翻译文本位置

### ISSUE THREAD

**Issue by hhyacg** [luojunyuan/ErogeHelper#6]
往后能不能增加个文本居中功能？

**Comment by luojunyuan** [comment]
目前我用的StackPanel来布局日文和翻译文本。似乎不太好改居中。
现在可以用自由移动的窗口，而不是固定在上方的文本。

最初我考虑的是日文原文在平板上，刚好平板有上下两条黑边来放多余的文本而不会影响游戏画面。
并且在8寸至10寸的设备上，去看上方的文本也不会显得很费劲，因为EH主要是辅助的作用，正常使用的时候应该不需要盯着上方文本。
然后后来加窗口越加越乱了。。希望以后可以改回来

**Comment by hhyacg** [comment]
我的想法是文本居中就能像字幕一样，我vnr是这么设置的
