### ISSUE TITLE
能否加一个修改外部文本窗口的透明度和背景颜色的功能？

### ISSUE THREAD

**Issue by rxia24** [luojunyuan/ErogeHelper#7]
看了您以前的issue, 应该是在平板上使用比较多，

桌面模式下，一般都是窗口运行，
如果可以调整背景颜色和透明度的话，加上有原文和平假名注释。
可以更好取代游戏原本的文本框，而不会被干扰。

![image](https://user-images.githubusercontent.com/22437401/120316036-906e3700-c30f-11eb-85f3-cd411bf26bea.png)

**Comment by luojunyuan** [comment]
会在项目重构后增加像vnr一样高度自定义、个性化文本框的设置选项。（暂时没时间继续改进了。。只得馒馒来）

我也有过使用提取出来的文本来替代原文文本阅读的想法，不过提取文本虽然速度很快，但始终会有比游戏慢一拍的感觉。即使是把文本速度调整到最快（不同钩子或游戏引擎当调快游戏文本速度时可能可以提高提取速度）。

另外关于文本窗口，背景全透明后该如何拖动（移动）文本框。我想过
1. 像vnr一样鼠标停留在一个特定区域（文字上放某一小部分区域）就会显示出一个bar可供拖动。
2. 保持当前透明度的顶部可供拖动的长条。其他文本部分可任意调整透明度。
3. 保持当前方式，让整个窗口全透明但是是鼠标不穿透（调整opacity至0.04左右可以实现这个效果的样子）。这样鼠标可以继续点击老位置拖动（但是肉眼看不见不知效果如何）。
4. 让整个文本窗口变得可以拖动，不与查词的左键冲突。

关羽显示历史文本的功能。vnr是可以保留和显示历史文本的，有一个上下滑动的滑条比较方便的就能看到之前的文本，并且移动到下一文本就可以正常归位显示新的文本。eh也想要还原这个。在不影响和游戏正常交互的情况下又能方便地看到之前的历史原文文本皆翻译。这个也需要和上面透明实现结合起来考虑我想。yuki是左右加一个按钮来切换文本，我感觉还是不太实用。

**Comment by rxia24** [comment]
感谢你的回复！

我的建议只是一些个人的想法，希望还是按照自己的想法和计划来。
我因为完全不懂C#，就试着改了下。

关于全透明之后怎么拖动，我尝试直接在设置里加个可以调整Opacity的slider。
可惜不懂怎么传参。。。
![image](https://user-images.githubusercontent.com/22437401/120328765-bc90b480-c31d-11eb-8b55-0b385994dd4c.png)

既然你有重构的计划，那就保持原样吧。
历史文本什么的可以放到很后面再说。

当前的已经够好了，我真的特别喜欢这个可以右键直接通过LE启动。
因为我的游戏太多，YUKI和Misaka都不适合直接当游戏库。
只得在Playnite里用LE当作模拟器去启动游戏。
ErogeHelper也能在Playnite中启动游戏，解决了我不知道怎么管理和启动翻译器的痛点。

**Comment by luojunyuan** [comment]
现在的机翻软件 luna蛮好的，老外还做了个JL(wpf) 用来查词，但是都没还原vnr一批巨好玩的功能包括服务器，估计以后也不会有人做。~~再等过几年有空了~~想用fsharp+avalonia重开个项目，脑子想法还很多，_ (:з」∠)_ 坐守net8，还能支持到win7。
